# Generated by Django 4.0.3 on 2022-04-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
