# Generated by Django 4.0.3 on 2022-12-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_urlshortener_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlshortener',
            old_name='longurl',
            new_name='long_url',
        ),
        migrations.RenameField(
            model_name='urlshortener',
            old_name='shorturl',
            new_name='short_url',
        ),
        migrations.RemoveField(
            model_name='urlshortener',
            name='count',
        ),
    ]
