# Generated by Django 4.0.3 on 2022-12-30 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_longurl_urlshortener_long_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
